export {default as Title} from "./image/titl.jpg";
export {default as Chordify} from "./image/chordify.png";
export {default as Lyricly} from "./image/lyricly.png";
export {default as OnlineWhite} from "./image/online.png";
export {default as Cat} from "./image/Gitcat.png";
export {default as Email} from "./image/email.png";
export {default as Resume} from "./image/resume.png";
export {default as HTML} from "./image/html.png";
export {default as Javascript} from "./image/javascript.png";
export {default as CSS} from "./image/css.png";
export {default as Reacts} from "./image/react.png";
export {default as Type} from "./image/type.png";
export {default as Sass} from "./image/sass.png";
export {default as Git} from "./image/git.png";
export {default as Photo} from "./image/affinityphoto.png";
export {default as Designer} from "./image/affinitydesigner.png";
export {default as Node} from "./image/node.png"
export {default as Frontend} from "./image/frontendLarge.png"
export {default as Arrow} from "./image/arrow.png"
export {default as Copy} from "./image/copy.png"
export {default as GithubCat} from "./image/githubcat.png"
export {default as Concurrent} from "./image/concurrent.png"
export {default as Bootstrap} from "./image/bootstrap.png"
export {default as AudioVis} from "./image/audiovis.png"